# Generated by Django 4.2.8 on 2023-12-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="name", new_name="author_name",
        ),
    ]
