# Generated by Django 4.2.8 on 2023-12-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_app", "0002_rename_name_item_author_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="author_name", new_name="name",
        ),
    ]
